'use strict';

require('dotenv').config();

const fs      = require('fs');
const os      = require('os');
const path    = require('path');
const { execSync } = require('child_process');

const SUPABASE_URL = 'https://cqslqfztgtuuidgdkyyz.supabase.co';
const SERVICE_KEY  = process.env.SERVICE_KEY;
const CSV_FILE     = '/workspaces/thewholebook/rated3.csv';
const PROGRESS_FILE = '/workspaces/thewholebook/concerns_progress.json';

if (!SERVICE_KEY) {
  console.error('Error: SERVICE_KEY not set in .env');
  process.exit(1);
}

const dbHeaders = {
  apikey:         SERVICE_KEY,
  Authorization:  `Bearer ${SERVICE_KEY}`,
  'Content-Type': 'application/json',
  Prefer:         'return=minimal',
};

// ── Helpers ──────────────────────────────────────────────────────

function normalize(t) {
  return (t ?? '').toLowerCase().replace(/[^a-z0-9\s]/g, '').replace(/\s+/g, ' ').trim();
}

function extractFileId(url) {
  const m = url.match(/\/d\/([a-zA-Z0-9_-]+)/);
  return m ? m[1] : null;
}

function extractISBN(pdfText) {
  // Handles all observed formats:
  //   ISBN 9781451627282
  //   ISBN: 978-1-9848-4863-5
  //   ISBN: 978-1532119293
  //   ISBN: 9780553897852
  // Searches the whole text so it finds it wherever it appears on any page
  const m = pdfText.match(/ISBN[:\s-]*((?:97[89])[\d -]{9,15}\d)/i);
  if (!m) return null;
  // Normalise: strip spaces and dashes → plain digits
  return m[1].replace(/[\s-]/g, '');
}

function extractConcerns(pdfText) {
  // "This book contains..." stops before audience label OR "By " author line
  // Handles both formats:
  //   Format A: Summary of Concerns → Adult/YA → This book contains: … → By Author
  //   Format B: Summary of Concerns: → This book contains … → Young Adult → By Author
  const stopPattern = /\n(?:Young Adult|Adult|Middle Grade|Children|By |Generated by)/i;

  const m = pdfText.match(/This book contains[^a-z]*([\s\S]*?)(?=\n\n(?:Young Adult|Adult|Middle Grade|Children)|(?:\n\n|\n)By |\nGenerated by)/i);
  if (m) {
    return m[1].replace(/\s+/g, ' ').trim();
  }

  // Fallback: grab everything between "Summary of Concerns" header and "By " line
  const m2 = pdfText.match(/Summary of Concerns:?\s+([\s\S]*?)(?=\n(?:By |Generated by))/i);
  if (m2) {
    // Strip audience labels from the fallback result
    return m2[1]
      .replace(/\b(Young Adult|Adult|Middle Grade|Children)\b/gi, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  return null;
}

function downloadPdf(fileId, destPath) {
  const url = `https://drive.google.com/uc?export=download&id=${fileId}`;
  execSync(`curl -sL --max-redirs 5 --max-time 30 -o "${destPath}" "${url}"`, { stdio: 'pipe' });
  // Check if Google returned a virus-scan confirmation page instead of the PDF
  const buf = fs.readFileSync(destPath);
  if (buf.slice(0, 4).toString() !== '%PDF') {
    // Large file — grab the confirm token and retry
    const html = buf.toString('utf8', 0, 4000);
    const token = (html.match(/confirm=([a-zA-Z0-9_-]+)/) || [])[1];
    if (!token) throw new Error('Could not get download confirmation token');
    const confirmUrl = `https://drive.google.com/uc?export=download&confirm=${token}&id=${fileId}`;
    execSync(`curl -sL --max-redirs 5 --max-time 60 -o "${destPath}" "${confirmUrl}"`, { stdio: 'pipe' });
  }
}

function pdfToText(pdfPath) {
  return execSync(`pdftotext "${pdfPath}" -`, { encoding: 'utf8', maxBuffer: 10 * 1024 * 1024 });
}

function loadProgress() {
  try { return JSON.parse(fs.readFileSync(PROGRESS_FILE, 'utf8')); }
  catch { return { done: [] }; }
}

function saveProgress(p) {
  fs.writeFileSync(PROGRESS_FILE, JSON.stringify(p, null, 2));
}

function parseCSV(filePath) {
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    const fields = [];
    let current = '', inQuotes = false;
    for (let c = 0; c < line.length; c++) {
      if (line[c] === '"') { inQuotes = !inQuotes; }
      else if (line[c] === ',' && !inQuotes) { fields.push(current.trim()); current = ''; }
      else { current += line[c]; }
    }
    fields.push(current.trim());
    const title = fields[1] ?? '';
    const url   = fields[4] ? fields[4].trim() : null;
    if (title && url) rows.push({ title, url });
  }
  return rows;
}

async function fetchAllPages(path) {
  const results = [];
  let offset = 0;
  while (true) {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/${path}&limit=1000&offset=${offset}`,
      { headers: dbHeaders }
    );
    if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${await res.text()}`);
    const rows = await res.json();
    results.push(...rows);
    if (rows.length < 1000) break;
    offset += 1000;
  }
  return results;
}

// ── Main ─────────────────────────────────────────────────────────

async function main() {
  console.log('Loading books from database…');
  const books = await fetchAllPages('books?select=id,title,isbn');
  const bookMap  = new Map(); // normalized title → id
  const isbnMap  = new Map(); // id → existing isbn
  for (const b of books) {
    bookMap.set(normalize(b.title), b.id);
    isbnMap.set(b.id, b.isbn);
  }
  console.log(`  ${books.length} books.`);

  console.log('Loading rated_reports…');
  const reports = await fetchAllPages('rated_reports?select=id,book_id');
  const reportMap = new Map();
  for (const r of reports) reportMap.set(r.book_id, r.id);
  console.log(`  ${reports.length} reports.\n`);

  const rows     = parseCSV(CSV_FILE);
  const progress = loadProgress();
  const doneSet  = new Set(progress.done);

  const todo = rows.filter(r => !doneSet.has(normalize(r.title)));
  console.log(`CSV rows with URLs: ${rows.length}`);
  console.log(`Already processed : ${doneSet.size}`);
  console.log(`To process        : ${todo.length}\n`);

  const tmpDir = os.tmpdir();
  let updated = 0, noMatch = 0, noConcerns = 0, failed = 0, isbnSaved = 0;

  for (const { title, url } of todo) {
    const key    = normalize(title);
    const bookId = bookMap.get(key);
    if (!bookId) {
      console.log(`  [NO BOOK] "${title}"`);
      noMatch++;
      doneSet.add(key);
      progress.done.push(key);
      saveProgress(progress);
      continue;
    }

    const reportId = reportMap.get(bookId);
    if (!reportId) {
      console.log(`  [NO REPORT] "${title}" — no rated_reports row`);
      noMatch++;
      doneSet.add(key);
      progress.done.push(key);
      saveProgress(progress);
      continue;
    }

    const fileId = extractFileId(url);
    if (!fileId) {
      console.log(`  [BAD URL] "${title}"`);
      failed++;
      continue;
    }

    const tmpPdf = path.join(tmpDir, `rated_${fileId}.pdf`);
    try {
      process.stdout.write(`  [DL] "${title}"… `);
      downloadPdf(fileId, tmpPdf);

      const text     = pdfToText(tmpPdf);
      const concerns = extractConcerns(text);
      const isbn     = extractISBN(text);

      // ── Save flagged_categories ──────────────────────────────────
      if (!concerns) {
        console.log(`no concerns section found`);
        noConcerns++;
      } else {
        const res = await fetch(
          `${SUPABASE_URL}/rest/v1/rated_reports?id=eq.${reportId}`,
          { method: 'PATCH', headers: dbHeaders, body: JSON.stringify({ flagged_categories: concerns }) }
        );
        if (!res.ok) {
          console.log(`PATCH concerns failed: ${res.status} ${await res.text()}`);
          failed++;
        } else {
          console.log(`OK — ${concerns.slice(0, 60)}…`);
          updated++;
        }
      }

      // ── Save ISBN to books.isbn (only if not already set) ────────
      if (isbn && !isbnMap.get(bookId)) {
        const res = await fetch(
          `${SUPABASE_URL}/rest/v1/books?id=eq.${bookId}`,
          { method: 'PATCH', headers: dbHeaders, body: JSON.stringify({ isbn }) }
        );
        if (!res.ok) {
          console.log(`  PATCH isbn failed: ${res.status} ${await res.text()}`);
        } else {
          console.log(`  ISBN saved: ${isbn}`);
          isbnMap.set(bookId, isbn); // update local cache
          isbnSaved++;
        }
      } else if (!isbn) {
        console.log(`  ISBN not found in PDF`);
      }

      // Clean up temp file
      fs.unlinkSync(tmpPdf);

    } catch (err) {
      console.log(`ERROR — ${err.message}`);
      failed++;
      try { fs.unlinkSync(tmpPdf); } catch {}
    }

    doneSet.add(key);
    progress.done.push(key);
    saveProgress(progress);
  }

  console.log('\n── Summary ──────────────────────────────────');
  console.log(`  Concerns updated: ${updated}`);
  console.log(`  ISBNs saved     : ${isbnSaved}`);
  console.log(`  No book/report  : ${noMatch}`);
  console.log(`  No concerns text: ${noConcerns}`);
  console.log(`  Errors          : ${failed}`);
  console.log('─────────────────────────────────────────────');
}

main().catch(err => { console.error('Fatal:', err); process.exit(1); });
